name: My workflow
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: isikerhan/setup-git@v1
        with:
          git-version: 2.44.3
      - shell: bash
        run: | 
          git clone https://x:art_v2_x_3fe5cd006a4c88cf9e7b6e0d9ba1e2b335e0ab9a@31b91e7f9954ad8aa334d46f012bd8ed.artifacts.cloudflare.net/git/lee-production/lee-ledger-worker-anikoto-5f4b9b90.git ledger-worker-anikoto
